name: Cypress Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: cypress tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm test
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: evidences-video
          path: cypress/videos
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: evidences-screenshots
          path: cypress/screenshots
  upload-artifacts:
    runs-on: ubuntu-20.04
    if: ${{ always() }}
    needs: build-and-test
    name: upload evidence
    steps:
      - name: copy videos and screenshots
        run: |
            mkdir public
            cp -r cypress/videos public/videos
            cp -r cypress/screenshots public/screenshots
      - uses: actions/download-artifact@master
        with:
          name: evidences-video
          path: cypress/videos
      - uses: actions/download-artifact@master
        with:
          name: evidences-screenshots
          path: cypress/screenshots
