name: Cypress Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: cypress tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm test
