name: Cypress Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: cypress tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm test
  upload-artifacts:
    runs-on: ubuntu-20.04
    name: upload evidence
    steps:
      - name: copy videos and screenshots
        run: |
            mkdir public
            cp -r cypress\videos public\videos
            cp -r cypress\screenshots public\screenshots
  
